# Generated by Django 4.1.5 on 2023-01-04 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(max_length=150)),
                ('description', models.TextField(verbose_name='Описание')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_content_modules', to='course.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Контент модуль',
                'verbose_name_plural': 'Контент модули',
                'ordering': ['course'],
            },
        ),
        migrations.CreateModel(
            name='TestModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(max_length=150)),
                ('description', models.TextField(verbose_name='Описание')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_test_modules', to='course.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Тест модуль',
                'verbose_name_plural': 'Тест модули',
            },
        ),
        migrations.RemoveField(
            model_name='image',
            name='module',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='module',
        ),
        migrations.RemoveField(
            model_name='question',
            name='name',
        ),
        migrations.RemoveField(
            model_name='text',
            name='module',
        ),
        migrations.RemoveField(
            model_name='text',
            name='name',
        ),
        migrations.RemoveField(
            model_name='video',
            name='module',
        ),
        migrations.RemoveField(
            model_name='video',
            name='name',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.AddField(
            model_name='image',
            name='content_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='course.contentmodule', verbose_name='Модуль'),
        ),
        migrations.AddField(
            model_name='question',
            name='content_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='course.contentmodule', verbose_name='Модуль'),
        ),
        migrations.AddField(
            model_name='question',
            name='test_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_module_questions', to='course.testmodule', verbose_name='Тест модуль'),
        ),
        migrations.AddField(
            model_name='text',
            name='content_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='course.contentmodule', verbose_name='Модуль'),
        ),
        migrations.AddField(
            model_name='video',
            name='content_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='course.contentmodule', verbose_name='Модуль'),
        ),
    ]
